version: '3'

networks:
  agilengine:

services:
  mysql:
    image: mysql:5.7.22
    container_name: agilengine-db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ~/docker/agilengine:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - agilengine
